### ISSUE TITLE
How two way communication works

### ISSUE THREAD

**Issue by emi-emi671** [ybjozee/Twilio-Voice-Demo#1]
I tried this sample code and it is working with my trial account as I received an incoming call on my registered number. I have one question, is the same code enough to use the 2-way communication from mobile phone to the web app?

**Comment by ybjozee** [comment]
Hi, 

I'm really sorry for replying late.

The sample code shows how you can implement one-way communication (from the app to the user). To implement 2-way WhatsApp communication requires a few more things. 

I wrote on doing this (albeit with Symfony instead of Go). You can have a look at the tutorial [here](https://www.twilio.com/en-us/blog/integrate-twilio-whatsapp-business-api-with-symfony-application) and see if you can port the code to Go. 

Please let me know if you have any further questions.
